name       = "cpython"
remote     = "https://github.com/python/cpython.git"
commit     = "34439b8a25eecd5b0da8f653fec286dadb60ba62"
files      = 3556
extensions = ["py", "c", "h", "html", "js", "bat", "sh", "m"]
tolerance  = "1%"
